const LEADS_DATA = [
  {
    "name": "Sarah Johnson",
    "email": "sarah.johnson@brighttech.io",
    "company_name": "BrightTech",
    "job_title": "VP of Sales",
    "message": "We're scaling our sales team from 10 to 50 reps in Q2 and need a CRM with AI-powered lead routing and automation. Budget is pre-approved at $50K annually. Can we schedule a demo this week?",
    "lead_score": 91,
    "industry": "SaaS",
    "business_need": "Rapid sales team scaling requires CRM automation and AI-powered lead routing to handle 5x headcount growth in one quarter.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:32:05 UTC"
  },
  {
    "name": "Robert Martinez",
    "email": "r.martinez@scaleforce.io",
    "company_name": "ScaleForce",
    "job_title": "Chief Revenue Officer",
    "message": "Our current sales automation stack costs $200K/year and underperforms. I have authority to sign a replacement contract by Q3. Looking for a demo and pricing proposal ASAP.",
    "lead_score": 89,
    "industry": "SaaS",
    "business_need": "Replacing an underperforming $200K/year sales automation stack — decision-maker with signing authority and a clear Q3 deadline.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:32:18 UTC"
  },
  {
    "name": "James Wilson",
    "email": "j.wilson@eduflow.com",
    "company_name": "EduFlow",
    "job_title": "Chief Product Officer",
    "message": "We serve 2 million students and are rebuilding our LMS from scratch. This is a $5M initiative and I am leading vendor selection. Can we schedule a technical deep-dive session next week?",
    "lead_score": 86,
    "industry": "Education",
    "business_need": "Leading a $5M LMS rebuild for a 2M-student platform — actively in vendor selection with budget and authority confirmed.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:32:31 UTC"
  },
  {
    "name": "Amanda Foster",
    "email": "a.foster@precisionmfg.com",
    "company_name": "PrecisionMfg",
    "job_title": "VP of Operations",
    "message": "We operate 12 manufacturing plants on legacy ERP. Downtime is costing roughly $1M per month. We need a modern operations solution urgently and are ready to move fast if the ROI case is strong.",
    "lead_score": 85,
    "industry": "Manufacturing",
    "business_need": "Legacy ERP across 12 plants causing $1M/month in downtime losses — urgent need with strong ROI motivation and VP-level authority.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:32:44 UTC"
  },
  {
    "name": "Michael Chen",
    "email": "m.chen@healthflow.com",
    "company_name": "HealthFlow",
    "job_title": "CTO",
    "message": "We're building a HIPAA-compliant patient management platform and need a secure API integration layer. Our engineering team is ready. Looking to finalize a Q1 contract. Please send technical specs and pricing.",
    "lead_score": 88,
    "industry": "Healthcare",
    "business_need": "Needs a HIPAA-compliant API integration layer for a patient management platform — technical decision-maker with Q1 contract deadline.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:32:57 UTC"
  },
  {
    "name": "Jennifer Williams",
    "email": "jwilliams@novapay.com",
    "company_name": "NovaPay",
    "job_title": "CEO",
    "message": "NovaPay is expanding into 3 new markets next quarter and needs a payment processing partner handling multi-currency and real-time fraud detection. I am the decision-maker. When can we get on a call?",
    "lead_score": 87,
    "industry": "Finance",
    "business_need": "Expanding into 3 new markets requiring multi-currency payment processing and fraud detection — CEO with full decision-making authority.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:33:10 UTC"
  },
  {
    "name": "David Thompson",
    "email": "d.thompson@propelrealty.com",
    "company_name": "PropelRealty",
    "job_title": "CFO",
    "message": "Managing $2B in assets across 500+ properties. Our financial reporting is entirely manual and error-prone. I need an automated solution. Budget is available. Please send a proposal with implementation timeline.",
    "lead_score": 83,
    "industry": "Real Estate",
    "business_need": "Manual financial reporting for $2B in real estate assets is error-prone and unscalable — CFO with confirmed budget seeking automation.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:33:23 UTC"
  },
  {
    "name": "Lisa Park",
    "email": "l.park@cartking.com",
    "company_name": "CartKing",
    "job_title": "VP of Marketing",
    "message": "We run $10M/month in ad spend and conversion rates have dropped 18% YoY. I need an AI-driven personalization and segmentation engine deployed before Black Friday. Who should I speak with?",
    "lead_score": 82,
    "industry": "E-commerce",
    "business_need": "18% YoY conversion decline on $10M/month ad spend demands an AI personalization engine — VP-level urgency with a hard Black Friday deadline.",
    "recommended_action": "Schedule demo call with senior sales rep",
    "processed_at": "2026-04-14 10:33:36 UTC"
  },
  {
    "name": "Rachel Green",
    "email": "r.green@cloudsync.io",
    "company_name": "CloudSync",
    "job_title": "Business Development Manager",
    "message": "I spotted your booth at SaaStr and thought there might be some overlap between what we do. I'm open to a conversation to see if there's a potential fit or partnership angle worth exploring.",
    "lead_score": 58,
    "industry": "SaaS",
    "business_need": "Early-stage exploration of potential product fit or partnership — some commercial intent but no specific pain point articulated yet.",
    "recommended_action": "Send personalised case study and schedule follow-up call",
    "processed_at": "2026-04-14 10:33:49 UTC"
  },
  {
    "name": "Tom Rodriguez",
    "email": "t.rodriguez@logifreight.com",
    "company_name": "LogiFreight",
    "job_title": "Sales Manager",
    "message": "Our current CRM is causing real friction for the team and we're considering switching. We're about 20 reps. What does your onboarding process look like and what's the typical ramp time?",
    "lead_score": 55,
    "industry": "Logistics",
    "business_need": "20-person sales team experiencing CRM friction — actively evaluating alternatives, mid-level authority, no budget signal yet.",
    "recommended_action": "Send personalised case study and schedule follow-up call",
    "processed_at": "2026-04-14 10:34:02 UTC"
  },
  {
    "name": "Chris Brown",
    "email": "c.brown@shopbright.com",
    "company_name": "ShopBright",
    "job_title": "Marketing Manager",
    "message": "Hi, I came across your product and thought it might be useful for our team. We're a mid-sized retailer with a decent marketing budget. Could you send over some pricing information?",
    "lead_score": 52,
    "industry": "E-commerce",
    "business_need": "Mid-sized retailer with marketing budget exploring tools — interest is general with no specific pain point or urgency expressed.",
    "recommended_action": "Send personalised case study and schedule follow-up call",
    "processed_at": "2026-04-14 10:34:15 UTC"
  },
  {
    "name": "Sophie Anderson",
    "email": "s.anderson@techadvisors.com",
    "company_name": "TechAdvisors",
    "job_title": "Account Manager",
    "message": "One of my clients mentioned they might need your services. I'm doing some early research before looping them in. Could you share a few relevant case studies so I can assess the fit?",
    "lead_score": 47,
    "industry": "Consulting",
    "business_need": "Researching on behalf of an unnamed client — indirect lead with no confirmed need or budget, but could open a door to a real prospect.",
    "recommended_action": "Send personalised case study and schedule follow-up call",
    "processed_at": "2026-04-14 10:34:28 UTC"
  },
  {
    "name": "Emily Davis",
    "email": "e.davis@medcore.net",
    "company_name": "MedCore",
    "job_title": "IT Manager",
    "message": "We're evaluating vendors for our annual IT infrastructure refresh. Your solution was mentioned in a comparison article. Could you send me some documentation and a product overview?",
    "lead_score": 48,
    "industry": "Healthcare",
    "business_need": "Annual IT refresh underway — awareness from a comparison article suggests early-stage evaluation with potential budget but no urgency.",
    "recommended_action": "Send personalised case study and schedule follow-up call",
    "processed_at": "2026-04-14 10:34:41 UTC"
  },
  {
    "name": "Nancy Kim",
    "email": "n.kim@learnsmart.io",
    "company_name": "LearnSmart",
    "job_title": "Product Manager",
    "message": "I'm in early research mode exploring analytics capabilities for our platform. Still comparing a few vendors. Would love a high-level overview before we move further in our evaluation.",
    "lead_score": 45,
    "industry": "Education",
    "business_need": "Early-stage vendor comparison for analytics tooling — no timeline or budget confirmed, limited decision-making authority.",
    "recommended_action": "Add to email nurture sequence",
    "processed_at": "2026-04-14 10:34:54 UTC"
  },
  {
    "name": "Kevin Patel",
    "email": "k.patel@capgrowth.com",
    "company_name": "CapGrowth",
    "job_title": "Operations Manager",
    "message": "We're a financial services firm trying to streamline some back-office workflows. Not entirely sure if your product covers our use case, but wanted to learn more before bringing it to leadership.",
    "lead_score": 43,
    "industry": "Finance",
    "business_need": "Back-office workflow inefficiencies in a financial services firm — ops-level contact, no authority yet, needs escalation to leadership.",
    "recommended_action": "Add to email nurture sequence",
    "processed_at": "2026-04-14 10:35:07 UTC"
  },
  {
    "name": "Mark Thompson",
    "email": "m.thompson@steelworks.com",
    "company_name": "SteelWorks",
    "job_title": "HR Manager",
    "message": "Our HR team is looking for better workforce scheduling and management tools for our ~800-person manufacturing workforce. Not sure if this aligns with your product, but figured I'd reach out.",
    "lead_score": 42,
    "industry": "Manufacturing",
    "business_need": "Workforce scheduling pain for 800-person manufacturing site — HR-level authority, unclear product fit, exploratory contact.",
    "recommended_action": "Add to email nurture sequence",
    "processed_at": "2026-04-14 10:35:20 UTC"
  },
  {
    "name": "Daniel Lee",
    "email": "d.lee@freshmart.com",
    "company_name": "FreshMart",
    "job_title": "Marketing Coordinator",
    "message": "I handle our company's email and social channels and think we could use better marketing automation tools. Just starting to explore what's out there. No budget confirmed yet.",
    "lead_score": 35,
    "industry": "E-commerce",
    "business_need": "Marketing automation interest from a junior coordinator — no budget, no authority, very early discovery stage.",
    "recommended_action": "Send automated introduction email only",
    "processed_at": "2026-04-14 10:35:33 UTC"
  },
  {
    "name": "Tanya Brooks",
    "email": "t.brooks@retailchain.com",
    "company_name": "RetailChain",
    "job_title": "Customer Service Representative",
    "message": "Hi, I wanted to ask about your pricing tiers. Also, do you guys have a referral discount? Asking for a colleague who might be interested someday but hasn't committed to anything yet.",
    "lead_score": 22,
    "industry": "E-commerce",
    "business_need": "No personal buying intent — inquiring on behalf of an uncommitted colleague with no timeline or budget mentioned.",
    "recommended_action": "Send automated introduction email only",
    "processed_at": "2026-04-14 10:35:46 UTC"
  },
  {
    "name": "Alex Johnson",
    "email": "alex.j2024@gmail.com",
    "company_name": "University of Arizona",
    "job_title": "Student",
    "message": "Hi! I'm a marketing student working on a class project about AI in B2B sales. Would it be possible to get some information about how your platform works? It would really help my presentation.",
    "lead_score": 8,
    "industry": "Education",
    "business_need": "Student research project — no commercial intent, no budget, no company affiliation.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:35:59 UTC"
  },
  {
    "name": "Priya Sharma",
    "email": "priya.freelance@outlook.com",
    "company_name": "Self-Employed",
    "job_title": "Freelance Graphic Designer",
    "message": "Hey there, I do logo design and branding for small local businesses. I was wondering if you could help me set up a simple portfolio website. My budget is around $150-200 total.",
    "lead_score": 12,
    "industry": "Other",
    "business_need": "Personal portfolio website request from a solo freelancer — outside target market entirely, minimal budget.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:36:12 UTC"
  },
  {
    "name": "Jake Miller",
    "email": "jake.miller99@gmail.com",
    "company_name": "Personal Project",
    "job_title": "Junior Developer",
    "message": "Hey, saw you guys on Product Hunt — really cool! I'm just curious how your API works under the hood. I'm learning about AI integrations for a hobby side project. No budget or company involved.",
    "lead_score": 18,
    "industry": "Other",
    "business_need": "Hobbyist developer curiosity — no business, no budget, explicitly states no company involvement.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:36:25 UTC"
  },
  {
    "name": "Megan Williams",
    "email": "megan.w@stateu.edu",
    "company_name": "State University",
    "job_title": "Intern",
    "message": "Hi, I'm completing a summer internship and my supervisor gave us an assignment to contact five software vendors and summarize their offerings. Could you tell me about your main product features?",
    "lead_score": 6,
    "industry": "Education",
    "business_need": "Intern completing a class assignment — no purchasing intent, no authority, purely educational context.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:36:38 UTC"
  },
  {
    "name": "TestBot Crawler",
    "email": "noreply@test123.xyz",
    "company_name": "Test Company",
    "job_title": "N/A",
    "message": "test test 123 asdfgh please ignore this submission automated form fill",
    "lead_score": 2,
    "industry": "Other",
    "business_need": "Automated form submission / bot — not a real lead.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:36:51 UTC"
  },
  {
    "name": "Sean OBrien",
    "email": "sean.obrien.2025@gmail.com",
    "company_name": "N/A",
    "job_title": "Recent Graduate",
    "message": "I just graduated with a business degree and I'm actively job hunting. I noticed your company works in AI which I find exciting. Are there any entry-level openings? I'm a fast learner and very motivated.",
    "lead_score": 10,
    "industry": "Other",
    "business_need": "Job seeker, not a sales lead — submitted via sales inquiry form in error.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:36:58 UTC"
  },
  {
    "name": "Maria Santos",
    "email": "maria@localhomebakery.com",
    "company_name": "Local Home Bakery",
    "job_title": "Owner/Baker",
    "message": "Hi! I bake custom cakes from my home kitchen and want to get more local customers. Can your software help me get more followers on Instagram? I have maybe $40-50/month to spend on tools.",
    "lead_score": 15,
    "industry": "Other",
    "business_need": "Micro-business seeking Instagram growth tools — outside target market, negligible budget, no B2B fit.",
    "recommended_action": "Disqualify — no fit",
    "processed_at": "2026-04-14 10:37:05 UTC"
  }
];
